spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clientes_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always